// authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

// locations
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS';
export const ADD_LOCATION_FAILURE = 'ADD_LOCATION_FAILURE';
export const CLEAR_LOCATIONS_ERROR = 'CLEAR_LOCATIONS_ERROR';

// bikes
export const GET_ALL_BIKES_SUCCESS = 'GET_ALL_BIKES_SUCCESS';
export const GET_ALL_BIKES_FAILURE = 'GET_ALL_BIKES_FAILURE';
export const UPDATE_BIKE_SUCCESS = 'UPDATE_BIKE_SUCCESS';
export const UPDATE_BIKE_FAILURE = 'UPDATE_BIKE_FAILURE';
export const ADD_BIKE_SUCCESS = 'ADD_BIKE_SUCCESS';
export const ADD_BIKE_FAILURE = 'ADD_BIKE_FAILURE';
export const GET_USER_BIKE_SUCCESS = 'GET_USER_BIKE_SUCCESS';
export const GET_USER_BIKE_FAILURE = 'GET_USER_BIKE_FAILURE';
export const SET_USER_BIKE_SUCCESS = 'SET_USER_BIKE_SUCCESS';
export const SET_USER_BIKE_FAILURE = 'SET_USER_BIKE_FAILURE';
export const REMOVE_USER_BIKE_SUCCESS = 'REMOVE_USER_BIKE_SUCCESS';
export const REMOVE_USER_BIKE_FAILURE = 'REMOVE_USER_BIKE_FAILURE';
export const CLEAR_BIKES_ERROR = 'CLEAR_BIKES_ERROR';

// reports
export const GET_ALL_REPORTS_SUCCESS = 'GET_ALL_REPORTS_SUCCESS';
export const GET_ALL_REPORTS_FAILURE = 'GET_ALL_REPORTS_FAILURE';
export const SUBMIT_REPORT_SUCCESS = 'SUBMIT_REPORT_SUCCESS';
export const SUBMIT_REPORT_FAILURE = 'SUBMIT_REPORT_FAILURE';
export const CLEAR_REPORTS_ERROR = 'CLEAR_REPORTS_ERROR';